// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DarkModeContainer: typeof import('./src/components/common/DarkModeContainer/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HoverContainer: typeof import('./src/components/common/HoverContainer/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgFillLogo: typeof import('./src/components/common/SystemLogo/components/SvgFillLogo.vue')['default']
    SvgLogo: typeof import('./src/components/common/SystemLogo/components/SvgLogo.vue')['default']
    SystemLogo: typeof import('./src/components/common/SystemLogo/index.vue')['default']
  }
}

export {}
