// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DarkModeContainer: typeof import('./components/common/DarkModeContainer/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HoverContainer: typeof import('./components/common/HoverContainer/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgBanner: typeof import('./components/svg/SvgBanner.vue')['default']
    SvgEmptyData: typeof import('./components/svg/SvgEmptyData.vue')['default']
    SvgFillLogo: typeof import('./components/common/SystemLogo/components/SvgFillLogo.vue')['default']
    SvgLogo: typeof import('./components/common/SystemLogo/components/SvgLogo.vue')['default']
    SvgNetworkError: typeof import('./components/svg/SvgNetworkError.vue')['default']
    SvgNoPermission: typeof import('./components/svg/SvgNoPermission.vue')['default']
    SvgNotFound: typeof import('./components/svg/SvgNotFound.vue')['default']
    SvgServiceError: typeof import('./components/svg/SvgServiceError.vue')['default']
    SystemLogo: typeof import('./components/common/SystemLogo/index.vue')['default']
  }
}

export {}
